### ISSUE TITLE
Add the right-side drawer recipe

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#129]
https://github.com/sweetalert2/sweetalert2/issues/2059

https://codepen.io/Produkt/pen/vYGVRqP

**Comment by limonte** [comment]
https://sweetalert2.github.io/recipe-gallery/sidebars-drawers.html

**Comment by produktive** [comment]
@limonte fadeInRight still has unexpected behavior on mobile. Only on the fadeInRight animation. The rest look normal.
