### ISSUE TITLE
Rtl support

### ISSUE THREAD

**Issue by sody1981** [sweetalert2/sweetalert2.github.io#147]
I'm using bootstrap5 (mdbootstrap)
I tried using material, vanilla or bootstrap4 theme with no success.
Success icon seems odd i played with setuprtl ( add || document.dir == "rtl") so swal2-rtl is applied in the container but without success.. also progress bar from righ to left.

Appreciate help

Sami

**Comment by limonte** [comment]
Wrong repo, please report your issue here https://github.com/sweetalert2/sweetalert2/issues
