### ISSUE TITLE
Add documentation for swal.mixin()

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#15]
Mixins are probably the best recent feature in SweetAlert2, thanks, @zenflow :beers: 

Related release: https://github.com/sweetalert2/sweetalert2/releases/tag/v7.16.0

---

There's the Methods section: https://sweetalert2.github.io/#methods but I feel like `swal.mixin()` is too awesome to be there.

@zenflow do you maybe have any idea how can we split the Methods section into several subsections?

**Comment by zenflow** [comment]
@limonte It would be nice to have "static" methods and "instance" methods, but the lib doesn't *technically* have them yet, but maybe will, #1007. 

Also, having documentation elsewhere for isolated features of swal (e.g. queue, global-defaults) would improve the organization, but we don't technically have *isolated* features yet either. Until we properly isolate them (i.e. extract them into units we can layer on), they belong in the documentation for the one main unit. I think when you remove all the feature-related methods, you're left with: "getters", "setters", "actions".

**Comment by limonte** [comment]
Done in https://github.com/sweetalert2/sweetalert2.github.io/commit/095ed1ebc359f84137830af8729c04a6deba1dc2
