### ISSUE TITLE
Low contrast issues

### ISSUE THREAD

**Issue by patrickhlauke** [sweetalert2/sweetalert2.github.io#153]
There are various elements in the demo site that have a very low colour contrast. In particular, the links in the navigation (which, due to the `opacity: 0.7`, end up with an even lower/washed-out look), the "Try me" buttons (both when hovered and not). Suggest rethinking some of the colour choices, and abandoning the opacity change on hover in favour of some other visual style (e.g. for the left-hand navigation, keeping the links `opacity: 1`by default, and on hover adding an underline style to `nav a:hover span`).

**Comment by limonte** [comment]
Fixed all the contrast issues on the docs page, as well as released a new version of the library itself with fixed color contrast for buttons: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.2.1

Thank you for reporting @patrickhlauke!

**Comment by patrickhlauke** [comment]
good stuff. i'll have a look to check that nothing slipped through :)

made a note of a few more tiny things that i'll file separately (some are part of core sweetalert2, not just the documentation) ... but it's great to see this improving bit by bit 👍
