### ISSUE TITLE
Add documentation for inputValue as a Promise

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#17]
`inputValue` now could be a Promise (https://github.com/sweetalert2/sweetalert2/pull/1025)

Related release: https://github.com/sweetalert2/sweetalert2/releases/tag/v7.17.0

@gverni said that he will submit the PR with the documentation

**Comment by gverni** [comment]
Just submitted PR. @limonte you may want to change the title of the issue (it's referring to another feature)

**Comment by limonte** [comment]
> Just submitted PR. @limonte you may want to change the title of the issue (it's referring to another feature)

Oops, fixed. Thanks for the PR!

**Comment by limonte** [comment]
There's now the demo example and docs about `inputValue` as a promise, thus I'm closing this issue.
