### ISSUE TITLE
Content-Security-Policy and inline styles

### ISSUE THREAD

**Issue by tonyschwartz** [sweetalert2/sweetalert2.github.io#195]
SweetAlert2 uses inline styles and it shouldn't be doing that as a library.  The library can't be used when a strict Content Security Policy is employed.  

Browser (Chrome in this case) says:  Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by limonte** [comment]
The library is shipped in both styled and unstyled variants.

The unstyled one isn't using inline styles, here's how to use it:

```js
import Swal from 'sweetalert2/dist/sweetalert2.js'
```

And of course you'd need to include Swal styles separately for example using the `link` tag:

```html
<link rel="stylesheet" href="sweetalert2.min.css">
```

or by including it in your styles:

```
import 'sweetalert2/src/sweetalert2.scss'
```

Read more: https://sweetalert2.github.io/#usage

**Comment by tonyschwartz** [comment]
Perhaps this is not the place for this conversation, but the latest code does still fail.  The second line shown here (which is from the minified .js) fails at appendChild.  And line 7 as well.  I'm sure I may be doing something wrong and have missed a step, but I don't think so.

    var n = e.createElement("style");
    if (e.getElementsByTagName("head")[0].appendChild(n),
    n.styleSheet)
        n.styleSheet.disabled || (n.styleSheet.cssText = t);
    else
        try {
            n.innerHTML = t
        } catch (e) {
            n.innerText = t
        }

**Comment by limonte** [comment]
thanks for the feedback @tonyschwartz

**Comment by limonte** [comment]
can you confirm that v11.7.32 was ok and the latest version v11.10.6 has this issue?

**Comment by limonte** [comment]
`v11.10.6` doesn't have any `e.createElement("style")`:

https://cdn.jsdelivr.net/npm/sweetalert2@11.10.6/dist/sweetalert2.js

double-check everything and you'll be fine

**Comment by tonyschwartz** [comment]
I was using this: https://cdn.jsdelivr.net/npm/sweetalert2@11.10.6/dist/sweetalert2.all.min.js
per the install instructions found on https://sweetalert2.github.io/.  See download & install section.  It says, "Or grab from jsDelivr CDN".  If you follow that, you see: 
<script src="
https://cdn.jsdelivr.net/npm/sweetalert2@11.10.6/dist/sweetalert2.all.min.js
"></script>
<link href="
https://cdn.jsdelivr.net/npm/sweetalert2@11.10.6/dist/sweetalert2.min.css
" rel="stylesheet">

I'm sorry, I don't know the difference yet between sweetalert2.js and sweetalert2.all.js

Thank you for your help,

Tony
