### ISSUE TITLE
Syntax highlighting for code samples is manual

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2.github.io#28]
Contributors have to insert html tags into the code samples manually for syntax highlighting. Some problems with this:

1. It's very tedious and time consuming to write code samples. Besides being a huge pain, this discourages including code samples with documentation updates.
2. Syntax highlighting is inconsistent. Very much so in some places.
3. It's difficult to read the JS in a plaintext view (e.g. code editor, github)

Part of #1

**Comment by limonte** [comment]
Thanks to https://github.com/isagalaev/highlight.js this was quite easy to implement :tada:

**Comment by zenflow** [comment]
I'm really happy to see this issue fixed, as it was my biggest pain point working with this site. My only criticism is that the performance isn't optimal because the browser has to download that whole library and process the code samples each time the page loads, when it could be done in a build step.
