### ISSUE TITLE
Proposal for restructuring documentation page 

### ISSUE THREAD

**Issue by gverni** [sweetalert2/sweetalert2.github.io#43]
I think that with all the new APIs and example, the documentation page is becoming quite long and heavy (and maybe confusing). Moreover I was thinking to add some more advanced usage examples, such as:

* https://github.com/sweetalert2/sweetalert2/issues/1308
* https://github.com/sweetalert2/sweetalert2/issues/1294 (I love this one BTW :-)) 

Plus maybe we can add some of the example coming from stackoverflow solutions. 

If we all agree on adding these, then the documentation page may become very heavy, so we can break it into few pages, such as: 

* Getting started and basic examples 
* API and parameters documentation 
* Advanced examples 

Collaborators, what do you think? I can work on a proposal if you want to see it before approving.

**Comment by limonte** [comment]
Advanced examples are now in https://sweetalert2.github.io/recipe-gallery/

Everything else I'd prefer to stay the same for the sake of simplicity and ability to search the whole page with Ctrl+F.
