### ISSUE TITLE
Idea: Pull documentation from other repos

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2.github.io#5]
The idea is to have the build process here pull markdown from each library repo, for the topics like #configuration and #methods which are duplicated here and (1) are updated more frequently and (2) don't have a use for js/dhtml .

This would eliminate the duplication of effort and fix a lot of the pain of the disadvantage i describe here - https://github.com/sweetalert2/sweetalert2/issues/711#issuecomment-355611512

We would probably want to split up our documentation into multiple `.md` files though.

**Comment by acupajoe** [comment]
@zenflow to be clear, this would mean a uniform documentation layout for all the repos correct? Each repo would contain their own `documentation/*.md` that would be aggregated here?

**Comment by zenflow** [comment]
> to be clear, this would mean a uniform documentation layout for all the repos correct?

No

> Each repo would contain their own documentation/*.md that would be aggregated here?

Yes

No need for the organization to be uniform, and I think keeping that synced across repos could end up being a pain.

**Comment by zenflow** [comment]
Mainly I am just thinking about the content that is in tables, like "Configuration" (params) and "Methods". We could pull in that content and present it however we like. 

There is not even a need for those tables to be the same across repos. For example, one repo might have an extra column for "Type" in it's Configuration table. Another repo might not have any table for "Configuration".

That said, we could try modestly to keep them relatively uniform, since it seems to be more pleasing to nerds.

**Comment by zenflow** [comment]
Since documentation was removed from the core repo in #837, I think this is no longer necessary.

I think it's fine to have the documentation live only in this repo.

**Comment by zenflow** [comment]
I reopened this because at this moment it seems like our lives would be a bit easier/more-efficient if we had the documentation content live in the same Git repository as the things it's documenting.

If you look at the issues right now, you'll see that this repo is lagging behind the core repo, and a bunch of issues have piled up for changes that [if we pulled content from core repo] would have been included in their related PR in the core repo.

**Comment by limonte** [comment]
This is all cool and smart, but having a build process for the documentation of the plugin for popups/toasts seems like overengineering to me.

The current page is just fine, KISS.

> most systems work best if they are kept simple rather than made complicated; therefore simplicity should be a key goal in design and unnecessary complexity should be avoided

https://github.com/sweetalert2/sweetalert2.github.io/pull/20#issuecomment-398709548
