### ISSUE TITLE
View documentation for earlier versions?

### ISSUE THREAD

**Issue by thomastruett** [sweetalert2/sweetalert2.github.io#68]
I use sweetalert2 in projects quite regularly. There have been several occasions where version updates cause compatibility issues and I spend hours going through each of my projects to resolve them. I believe that in many cases it makes more sense for me to keep my existing version of sweetalert2 in place. I would do this, but that is challenging due to the fact that there is no longer documentation for me to reference for that particular version.

Am I missing this somewhere? Thanks!

**Comment by limonte** [comment]
https://sweetalert2.github.io/v7.html :tada:

**Comment by gverni** [comment]
Very useful @limonte! Should we add a link to that in the main page as well?

**Comment by limonte** [comment]
What do you mean by "main page"?

**Comment by gverni** [comment]
Sorry I wasn't clear. I meant putting a link to that from https://sweetalert2.github.io/

**Comment by gverni** [comment]
Sorry, it's actually there... but if i may could we put it a bit more in the center of the page? I looked at the page 3 times and i haven't seen it...

**Comment by gverni** [comment]
...or maybe before the social links at the bottom of the side menu. For some reason my eyes didn't go beyond that social links section... 

![image](https://user-images.githubusercontent.com/17089396/54438552-c1fa8800-472e-11e9-9818-ab088b0d44fd.png)

**Comment by limonte** [comment]
> could we put it a bit more in the center of the page? 

The importance of this selector is low, so I'm not if favor of giving it better positioning.

Showing people how to share the love is far more important for SweetAlert2  than version selector. We should not encourage devs to stick to prev versions. On the other hand, encouraging them to share the <3 is a good thing.

**Comment by gverni** [comment]
> On the other hand, encouraging them to share the <3 is a good thing.

I see your point... 👍
