### ISSUE TITLE
Move the "Timer functions example" to swetalert2-examples

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#73]
The "Timer functions example" is too big IMO to be in https://sweetalert2.github.io

@gverni  Do you agree to move it to `sweetalert2-examples`?

**Comment by limonte** [comment]
ping @gverni

**Comment by limonte** [comment]
Done in https://github.com/sweetalert2/sweetalert2.github.io/commit/26b0c423f91f8d87d65ee46526d200f1c02b1e92 and https://github.com/sweetalert2/sweetalert2-examples/commit/3f992ee6ea741ca5277663bfed408086d6b57688

**Comment by gverni** [comment]
Sorry @limonte i have no idea how i missed the mention... and the ping 😢 Thanks for this!
