### ISSUE TITLE
index.html & v7.html use the same js file

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2.github.io#74]
We have `v7.html` now as of 72a278780feaf42f5e477472b4c1a34b75e8f0ea, but no `src/app-v7.js`. The `v7.html` uses the the same js as `index.html` (source: `src/app.js`, built: `dist/bundle.js`).

I assume we want to be able to update the examples for newer versions. We can't currently do that without breaking the v7 page (representation/displayed code would not match executed code)

For example, the RTL example on the v7 page is completely broken because, although the displayed code is valid for v7, the executed code is only valid for v8.

I might suggest reverting 72a278780feaf42f5e477472b4c1a34b75e8f0ea and reopening #68 until we get a working solution.

**Comment by limonte** [comment]
Oops, totally missed that, thanks @zenflow 

No need in `src/app-v7.js`, `dist/bundle-v7.js` would be enough. Please do not consider v7 docs at all in any new feature, e.g. when implementing #27

**Comment by zenflow** [comment]
@limonte Now the version drop-down doesn't work on the v7 page.. I suggest moving this code into the html files: https://github.com/sweetalert2/sweetalert2.github.io/blob/b7374b7400b4e62925ac9b916ee94e00363f6773/src/app.js#L761-L770
