### ISSUE TITLE
Version drop-down doesn't work on v7 page

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2.github.io#75]
https://github.com/sweetalert2/sweetalert2.github.io/issues/74#issuecomment-480592638:
>@limonte Now the version drop-down doesn't work on the v7 page.. I suggest moving this code into the html files: https://github.com/sweetalert2/sweetalert2.github.io/blob/b7374b7400b4e62925ac9b916ee94e00363f6773/src/app.js#L761-L770

**Comment by limonte** [comment]
wontfix
