### ISSUE TITLE
Logo is incompatible with devices with width 360px 

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2.github.io#98]
![image](https://user-images.githubusercontent.com/6059356/62794376-9bbdf600-badc-11e9-8ab7-39a9549a06f3.png)

360px is the most popular (or one of the most popular) screen resolution for mobile devices, I believe we should support it in https://sweetalert2.github.io/

@gverni apologies for not catching this during the review. Would you mind taking care of this issue? I'll be fine with any solution, including removing the animation for narrow devices.

**Comment by gverni** [comment]
Thanks @limonte and sorry for the delay with the PR...
